### PR TITLE
Issue 7 - Add bootstrap to the project.

### LINKED ISSUE #7: Add bootstrap to the project.
We should use bootstrap for rapid development of the project by now. Probably in future we will move to our custom css/js based code.
Bootstrap support should be added through `npm` to this project.

### PR DESCRIPTION
**Pull request by Gosha2015**
Bootstrap is added to the project using bower

Fixes #7

### CODE REVIEW

**Comment by Gosha2015** [comment]
i used bower for get sources jQuery and bootstrap

**Comment by Gosha2015** [comment]
i used bower for get sources jQuery and bootstrap

**Comment by sshishov** [comment]
Firstly please add `bower_components` to git ignore list. They should not be under git control and should be installed manually from requirements file

**Comment by sshishov** [comment]
I updated summary and description, please note the correct syntax

**Comment by sshishov** [comment]
Why you merged? I did not check your pull request.
Also do not use MERGE button, use rebase instead.
If you do not know how to do it, please ask

**Comment by sshishov** [comment]
Reverting changes as they are incorrect and contains bower_components inside indexed files

**Comment by sshishov** [comment]
Please fix the issue again in new PR according to our rules:
- get LGTM label before merging
- rebase before merging to master (to avoid merge commits and plain history)
- apply all comments from your team members
- verify your fix before merging for debug/incorrect code

**Pull request merged**
